# This file was generated by GoReleaser. DO NOT EDIT.
class Fifo < Formula
  desc ""
  homepage ""
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/relvacode/fifo/releases/download/v0.1.1/fifo_0.1.1_osx_x86_64.tar.gz"
    sha256 "640dd756775322fc26495fdb852126eb9ea6825f4c280300686879ce22b5230c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/relvacode/fifo/releases/download/v0.1.1/fifo_0.1.1_linux_x86_64.tar.gz"
      sha256 "ef4d38f6478f41c4aeed432e721183e7159ec2bed0bfd3a0194b28a9d9ac285d"
    end
  end

  def install
    bin.install "fifo"
  end
end
